
#include "mcu.h"
#include "HAL_FM4_i2s.h"
#include "FM4_WM8731.h"


void I2S_init(char fs)
{
    bFM4_CLK_GATING_CKEN2_I2SCK0 = 1u; // supply clock to I2S peripheral.

    FM4_GPIO->EPFR24 |= (1ul << 0ul); // configure I2S0-MCLK pin as input
    bFM4_GPIO_PFR5_PD = 1u;

    FM4_GPIO->EPFR24 |= (1ul << 10ul); // configure I2S0-DO pin as output
    bFM4_GPIO_PFR5_PE = 1u;

    FM4_GPIO->EPFR24 |= (1ul << 8ul); // configure I2S0-DI pin as input
    bFM4_GPIO_PFR3_P0 = 1u;

    FM4_GPIO->EPFR24 |= (1ul << 4ul); // configure I2S0-CK pin as input/output (input used)
    bFM4_GPIO_PFR3_P1 = 1u;

    FM4_GPIO->EPFR24 |= (1ul << 6ul); // configure I2S0-WS pin as input/output (input used)
    bFM4_GPIO_PFR5_PF = 1u;

    bFM4_I2SPRE_ICCR_ICEN = 0u;    // disable MCLK output - clock will be generated by WM8731
    FM4_I2S0->OPRREG_f.START = 0u; // stop I2S interface while configuring
    FM4_I2S0->CNTREG_f.CKRT = 0u;  // bypass clock divider
    switch (fs)                    // configure overhead bits according to sampling rate
    {
    case FS_8000_HZ:
        FM4_I2S0->CNTREG_f.OVHD = 352;
        break;
    case FS_32000_HZ:
        FM4_I2S0->CNTREG_f.OVHD = 64;
        break;
    case FS_16000_HZ:
        FM4_I2S0->CNTREG_f.OVHD = 64;
        break;
    case FS_24000_HZ:
        FM4_I2S0->CNTREG_f.OVHD = 32;
        break;
    case FS_48000_HZ:
        FM4_I2S0->CNTREG_f.OVHD = 32;
        break;
    case FS_96000_HZ:
        FM4_I2S0->CNTREG_f.OVHD = 0;
        break;
    default:
        FM4_I2S0->CNTREG_f.OVHD = 352;
        break;
    }
    FM4_I2S0->CNTREG_f.MSKB = 0x00;  // no mask -bit
    FM4_I2S0->CNTREG_f.MSMD = 0x00;  // I2S slave mode
    FM4_I2S0->CNTREG_f.SBFN = 0x00;  // 1 subframe, 2 channels in subframe
    FM4_I2S0->CNTREG_f.RHLL = 0x01;  // 32-bit FIFO word comprises two 16-bit samples
    FM4_I2S0->CNTREG_f.MLSB = 0x00;  // shift starts from MSB of word
    FM4_I2S0->CNTREG_f.SMPL = 0x00;  // sample in middle of received data.
    FM4_I2S0->CNTREG_f.CPOL = 0x01;  // drive data at the falling edge and sample data at rising edge of I2SCK
    FM4_I2S0->CNTREG_f.FSPH = 0x00;  // I2SWS is enabled at the same time as the frame data and first bit
    FM4_I2S0->CNTREG_f.FSLN = 0x01;  // frame sync pulse width is one channel (16-bit sample)
    FM4_I2S0->CNTREG_f.FSPL = 0x00;  // I2SWS is "1", and the frame sync signal is enabled. This is "0" when idle.
    FM4_I2S0->MCR0REG_f.S0CHN = 1u;  // (number_of_channels - 1) for subframe 0 (two channels)
    FM4_I2S0->MCR0REG_f.S0CHL = 15u; // (bit_length - 1) of the channels that make up subframe 0
    FM4_I2S0->MCR0REG_f.S0WDL = 15u; // subframe 0 word length - 1
    FM4_I2S0->MCR1REG = 0x00000003u; // enable channels 0 and 1 in subframe 0

    // Transmit interrupt settings
    FM4_I2S0->INTCNT_f.TXUD0M = 0x01;
    FM4_I2S0->INTCNT_f.TXUD1M = 0x01;
    FM4_I2S0->INTCNT_f.TBERM = 0x01;
    FM4_I2S0->INTCNT_f.TXOVM = 0x01;

    FM4_I2S0->INTCNT_f.TXFDM = 0x01;
    FM4_I2S0->INTCNT_f.TXFIM = 0x00;
    FM4_I2S0->INTCNT_f.RXFDM = 0x01;
    FM4_I2S0->INTCNT_f.FERRM = 0x01;
    FM4_I2S0->INTCNT_f.RBERM = 0x01;
    FM4_I2S0->INTCNT_f.RXUDM = 0x01;
    FM4_I2S0->INTCNT_f.RXOVM = 0x01;
    FM4_I2S0->INTCNT_f.EOPM = 0x01;
    FM4_I2S0->INTCNT_f.RXFIM = 0x01;
    FM4_I2S0->INTCNT_f.RPTMR = 0x0;
}

uint32_t I2S_rx(void)
{
  return 	FM4_I2S0->RXFDAT; // read data from the receive FIFO register  
}

void I2S_tx(uint32_t c)
{
	FM4_I2S0->TXFDAT = c;     // write data to the transmit FIFO register 
}

void I2S_start (void)
{
    FM4_I2S0->OPRREG_f.START  = 1u ;            // start the I2S module
}

void I2S_loopback_enable (void)
{
    //FM4_I2S0->CNTREG_f.MSMD = 0x01;    // master slave mode
    FM4_I2S0->TSTREG = 1u ;            // start the I2S module
}

void I2S_loopback_disable (void)
{
    FM4_I2S0->TSTREG = 0u ;            // start the I2S module
}



